package by.training.taskobject.exception;